name: flutter_clipboard_manager_platform_interface
description: A common platform interface for the flutter_clipboard_manager plugin.
homepage: https://github.com/Taym95/flutter_clipboard_manager/blob/master/flutter_clipboard_manager_platform_interface
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.8.0
